; Sound Effects for song Sound effects, version 2.0, generated by Arkos Tracker 2.

SoundEffects:
SoundEffectsDisarkGenerateExternalLabel:

; The sound effects, starting at 1.
SoundEffectsDisarkPointerRegionStart0:
	defw SoundEffects_Sound1	; Sound effect 1.
	defw SoundEffects_Sound2	; Sound effect 2.
	defw 0	; Sound effect 3.
	defw 0	; Sound effect 4.
	defw 0	; Sound effect 5.
SoundEffectsDisarkPointerRegionEnd0:

SoundEffectsDisarkByteRegionStart1:
; Sound effect 1.
SoundEffects_Sound1:
	defb 0	; Speed

SoundEffects_Sound1_Loop:	defb 189	; Soft only. Volume: 15.
	defb 1	; Noise: 1.
	defw 95	; Software period.

	defb 189	; Soft only. Volume: 15.
	defb 1	; Noise: 1.
	defw 99	; Software period.

	defb 177	; Soft only. Volume: 12.
	defb 1	; Noise: 1.
	defw 102	; Software period.

	defb 173	; Soft only. Volume: 11.
	defb 1	; Noise: 1.
	defw 106	; Software period.

	defb 4	; End of the sound effect.

; Sound effect 2.
SoundEffects_Sound2:
	defb 1	; Speed

SoundEffects_Sound2_Loop:	defb 189	; Soft only. Volume: 15.
	defb 1	; Noise: 1.
	defw 301	; Software period.

	defb 189	; Soft only. Volume: 15.
	defb 8	; Noise: 8.
	defw 319	; Software period.

	defb 185	; Soft only. Volume: 14.
	defb 2	; Noise: 2.
	defw 402	; Software period.

	defb 181	; Soft only. Volume: 13.
	defb 16	; Noise: 16.
	defw 213	; Software period.

	defb 177	; Soft only. Volume: 12.
	defb 2	; Noise: 2.
	defw 225	; Software period.

	defb 173	; Soft only. Volume: 11.
	defb 2	; Noise: 2.
	defw 239	; Software period.

	defb 165	; Soft only. Volume: 9.
	defb 16	; Noise: 16.
	defw 358	; Software period.

	defb 157	; Soft only. Volume: 7.
	defb 31	; Noise: 31.
	defw 119	; Software period.

	defb 153	; Soft only. Volume: 6.
	defb 7	; Noise: 7.
	defw 80	; Software period.

	defb 4	; End of the sound effect.

SoundEffectsDisarkByteRegionEnd1:
